CATEGORIES = [
	"Account Management",
	"Business & Strategy",
	"Creative & Design",
	"Customer Service",
	"Data Science",
	"Editorial",
	"Education",
	"Engineering",
	"Finance & Data",
	"Fundraising & Development",
	"Healthcare & Medicine",
	"HR & Recruiting",
	"Legal",
	"Marketing & PR",
	"Operations",
	"Project & Product Management",
	"Retail",
	"Sales",
	"Social Media & Community",
]